# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'

pod 'Firebase/Messaging', '~> 6.3.0'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'organizeME' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for organizeME

  # target 'organizeME-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  target 'organizeMETests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'organizeME-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for organizeME-tvOS

#   target 'organizeME-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
